# Generated by Django 4.2.3 on 2023-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_pic', models.ImageField(upload_to='profile/')),
                ('short_bio', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='profile/cv')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
