# Generated by Django 4.2.3 on 2023-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='long_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
