# Generated by Django 4.2.3 on 2023-09-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_category_alter_contact_message_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='screenshots',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
