# Generated by Django 4.2.3 on 2023-09-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_projects_screenshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product_title',
            new_name='project_title',
        ),
        migrations.AlterModelTable(
            name='category',
            table='',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='',
        ),
    ]
