# Generated by Django 4.2.3 on 2023-10-20 03:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.IntegerField(primary_key=builtins.id, serialize=False),
        ),
    ]
