# Generated by Django 4.2.3 on 2023-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_blog_created_date_blog_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
